// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250106102510_PetCard")]
    partial class PetCard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.DogBreed", b =>
                {
                    b.Property<int>("BreedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BreedID"));

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BreedID");

                    b.ToTable("DogBreeds");

                    b.HasData(
                        new
                        {
                            BreedID = 1,
                            BreedName = "Affenpinscher"
                        },
                        new
                        {
                            BreedID = 2,
                            BreedName = "Airedale Terrier"
                        },
                        new
                        {
                            BreedID = 3,
                            BreedName = "Akita"
                        },
                        new
                        {
                            BreedID = 4,
                            BreedName = "Alaskan Malamute"
                        },
                        new
                        {
                            BreedID = 5,
                            BreedName = "American Bulldog"
                        },
                        new
                        {
                            BreedID = 6,
                            BreedName = "American Eskimo Dog"
                        },
                        new
                        {
                            BreedID = 7,
                            BreedName = "American Foxhound"
                        },
                        new
                        {
                            BreedID = 8,
                            BreedName = "American Pit Bull Terrier"
                        },
                        new
                        {
                            BreedID = 9,
                            BreedName = "American Staffordshire Terrier"
                        },
                        new
                        {
                            BreedID = 10,
                            BreedName = "Anatolian Shepherd"
                        },
                        new
                        {
                            BreedID = 11,
                            BreedName = "Australian Cattle Dog"
                        },
                        new
                        {
                            BreedID = 12,
                            BreedName = "Australian Shepherd"
                        },
                        new
                        {
                            BreedID = 13,
                            BreedName = "Barbet"
                        },
                        new
                        {
                            BreedID = 14,
                            BreedName = "Basenji"
                        },
                        new
                        {
                            BreedID = 15,
                            BreedName = "Basset Hound"
                        },
                        new
                        {
                            BreedID = 16,
                            BreedName = "Beagle"
                        },
                        new
                        {
                            BreedID = 17,
                            BreedName = "Bearded Collie"
                        },
                        new
                        {
                            BreedID = 18,
                            BreedName = "Beauceron"
                        },
                        new
                        {
                            BreedID = 19,
                            BreedName = "Bedlington Terrier"
                        },
                        new
                        {
                            BreedID = 20,
                            BreedName = "Belgian Malinois"
                        },
                        new
                        {
                            BreedID = 21,
                            BreedName = "Bernese Mountain Dog"
                        },
                        new
                        {
                            BreedID = 22,
                            BreedName = "Bichon Frise"
                        },
                        new
                        {
                            BreedID = 23,
                            BreedName = "Biewer Terrier"
                        },
                        new
                        {
                            BreedID = 24,
                            BreedName = "Bloodhound"
                        },
                        new
                        {
                            BreedID = 25,
                            BreedName = "Bluetick Coonhound"
                        },
                        new
                        {
                            BreedID = 26,
                            BreedName = "Boerboel"
                        },
                        new
                        {
                            BreedID = 27,
                            BreedName = "Bolognese"
                        },
                        new
                        {
                            BreedID = 28,
                            BreedName = "Border Collie"
                        },
                        new
                        {
                            BreedID = 29,
                            BreedName = "Border Terrier"
                        },
                        new
                        {
                            BreedID = 30,
                            BreedName = "Borzoi"
                        },
                        new
                        {
                            BreedID = 31,
                            BreedName = "Boston Terrier"
                        },
                        new
                        {
                            BreedID = 32,
                            BreedName = "Bouvier des Flandres"
                        },
                        new
                        {
                            BreedID = 33,
                            BreedName = "Boxer"
                        },
                        new
                        {
                            BreedID = 34,
                            BreedName = "Boykin Spaniel"
                        },
                        new
                        {
                            BreedID = 35,
                            BreedName = "Briard"
                        },
                        new
                        {
                            BreedID = 36,
                            BreedName = "Brittany"
                        },
                        new
                        {
                            BreedID = 37,
                            BreedName = "Brussels Griffon"
                        },
                        new
                        {
                            BreedID = 38,
                            BreedName = "Bull Terrier"
                        },
                        new
                        {
                            BreedID = 39,
                            BreedName = "Bulldog"
                        },
                        new
                        {
                            BreedID = 40,
                            BreedName = "Bullmastiff"
                        },
                        new
                        {
                            BreedID = 41,
                            BreedName = "Cairn Terrier"
                        },
                        new
                        {
                            BreedID = 42,
                            BreedName = "Cane Corso"
                        },
                        new
                        {
                            BreedID = 43,
                            BreedName = "Cardigan Welsh Corgi"
                        },
                        new
                        {
                            BreedID = 44,
                            BreedName = "Cavalier King Charles Spaniel"
                        },
                        new
                        {
                            BreedID = 45,
                            BreedName = "Chesapeake Bay Retriever"
                        },
                        new
                        {
                            BreedID = 46,
                            BreedName = "Chihuahua"
                        },
                        new
                        {
                            BreedID = 47,
                            BreedName = "Chinese Crested"
                        },
                        new
                        {
                            BreedID = 48,
                            BreedName = "Chinese Shar-Pei"
                        },
                        new
                        {
                            BreedID = 49,
                            BreedName = "Chinook"
                        },
                        new
                        {
                            BreedID = 50,
                            BreedName = "Chow Chow"
                        },
                        new
                        {
                            BreedID = 51,
                            BreedName = "Clumber Spaniel"
                        },
                        new
                        {
                            BreedID = 52,
                            BreedName = "Cocker Spaniel"
                        },
                        new
                        {
                            BreedID = 53,
                            BreedName = "Collie"
                        },
                        new
                        {
                            BreedID = 54,
                            BreedName = "Coton de Tulear"
                        },
                        new
                        {
                            BreedID = 55,
                            BreedName = "Dachshund"
                        },
                        new
                        {
                            BreedID = 56,
                            BreedName = "Dalmatian"
                        },
                        new
                        {
                            BreedID = 57,
                            BreedName = "Doberman Pinscher"
                        },
                        new
                        {
                            BreedID = 58,
                            BreedName = "Dogo Argentino"
                        },
                        new
                        {
                            BreedID = 59,
                            BreedName = "Dogue de Bordeaux"
                        },
                        new
                        {
                            BreedID = 60,
                            BreedName = "Dutch Shepherd"
                        },
                        new
                        {
                            BreedID = 61,
                            BreedName = "English Cocker Spaniel"
                        },
                        new
                        {
                            BreedID = 62,
                            BreedName = "English Setter"
                        },
                        new
                        {
                            BreedID = 63,
                            BreedName = "English Springer Spaniel"
                        },
                        new
                        {
                            BreedID = 64,
                            BreedName = "Entlebucher Mountain Dog"
                        },
                        new
                        {
                            BreedID = 65,
                            BreedName = "Flat-Coated Retriever"
                        },
                        new
                        {
                            BreedID = 66,
                            BreedName = "French Bulldog"
                        },
                        new
                        {
                            BreedID = 67,
                            BreedName = "German Pinscher"
                        },
                        new
                        {
                            BreedID = 68,
                            BreedName = "German Shepherd"
                        },
                        new
                        {
                            BreedID = 69,
                            BreedName = "German Shorthaired Pointer"
                        },
                        new
                        {
                            BreedID = 70,
                            BreedName = "German Wirehaired Pointer"
                        },
                        new
                        {
                            BreedID = 71,
                            BreedName = "Giant Schnauzer"
                        },
                        new
                        {
                            BreedID = 72,
                            BreedName = "Golden Retriever"
                        },
                        new
                        {
                            BreedID = 73,
                            BreedName = "Gordon Setter"
                        },
                        new
                        {
                            BreedID = 74,
                            BreedName = "Great Dane"
                        },
                        new
                        {
                            BreedID = 75,
                            BreedName = "Great Pyrenees"
                        },
                        new
                        {
                            BreedID = 76,
                            BreedName = "Greater Swiss Mountain Dog"
                        },
                        new
                        {
                            BreedID = 77,
                            BreedName = "Greyhound"
                        },
                        new
                        {
                            BreedID = 78,
                            BreedName = "Harrier"
                        },
                        new
                        {
                            BreedID = 79,
                            BreedName = "Havanese"
                        },
                        new
                        {
                            BreedID = 80,
                            BreedName = "Irish Setter"
                        },
                        new
                        {
                            BreedID = 81,
                            BreedName = "Irish Terrier"
                        },
                        new
                        {
                            BreedID = 82,
                            BreedName = "Irish Water Spaniel"
                        },
                        new
                        {
                            BreedID = 83,
                            BreedName = "Irish Wolfhound"
                        },
                        new
                        {
                            BreedID = 84,
                            BreedName = "Italian Greyhound"
                        },
                        new
                        {
                            BreedID = 85,
                            BreedName = "Jack Russell Terrier"
                        },
                        new
                        {
                            BreedID = 86,
                            BreedName = "Japanese Chin"
                        },
                        new
                        {
                            BreedID = 87,
                            BreedName = "Keeshond"
                        },
                        new
                        {
                            BreedID = 88,
                            BreedName = "Kerry Blue Terrier"
                        },
                        new
                        {
                            BreedID = 89,
                            BreedName = "Komondor"
                        },
                        new
                        {
                            BreedID = 90,
                            BreedName = "Kuvasz"
                        },
                        new
                        {
                            BreedID = 91,
                            BreedName = "Labrador Retriever"
                        },
                        new
                        {
                            BreedID = 92,
                            BreedName = "Lagotto Romagnolo"
                        },
                        new
                        {
                            BreedID = 93,
                            BreedName = "Lakeland Terrier"
                        },
                        new
                        {
                            BreedID = 94,
                            BreedName = "Leonberger"
                        },
                        new
                        {
                            BreedID = 95,
                            BreedName = "Lhasa Apso"
                        },
                        new
                        {
                            BreedID = 96,
                            BreedName = "Maltese"
                        },
                        new
                        {
                            BreedID = 97,
                            BreedName = "Manchester Terrier"
                        },
                        new
                        {
                            BreedID = 98,
                            BreedName = "Mastiff"
                        },
                        new
                        {
                            BreedID = 99,
                            BreedName = "Miniature Pinscher"
                        },
                        new
                        {
                            BreedID = 100,
                            BreedName = "Miniature Schnauzer"
                        },
                        new
                        {
                            BreedID = 101,
                            BreedName = "Neapolitan Mastiff"
                        },
                        new
                        {
                            BreedID = 102,
                            BreedName = "Nederlandse Kooikerhondje"
                        },
                        new
                        {
                            BreedID = 103,
                            BreedName = "Newfoundland"
                        },
                        new
                        {
                            BreedID = 104,
                            BreedName = "Norfolk Terrier"
                        },
                        new
                        {
                            BreedID = 105,
                            BreedName = "Norwegian Elkhound"
                        },
                        new
                        {
                            BreedID = 106,
                            BreedName = "Norwich Terrier"
                        },
                        new
                        {
                            BreedID = 107,
                            BreedName = "Nova Scotia Duck Tolling Retriever"
                        },
                        new
                        {
                            BreedID = 108,
                            BreedName = "Old English Sheepdog"
                        },
                        new
                        {
                            BreedID = 109,
                            BreedName = "Papillon"
                        },
                        new
                        {
                            BreedID = 110,
                            BreedName = "Pekingese"
                        },
                        new
                        {
                            BreedID = 111,
                            BreedName = "Pembroke Welsh Corgi"
                        },
                        new
                        {
                            BreedID = 112,
                            BreedName = "Pharaoh Hound"
                        },
                        new
                        {
                            BreedID = 113,
                            BreedName = "Plott Hound"
                        },
                        new
                        {
                            BreedID = 114,
                            BreedName = "Pointer"
                        },
                        new
                        {
                            BreedID = 115,
                            BreedName = "Pomeranian"
                        },
                        new
                        {
                            BreedID = 116,
                            BreedName = "Poodle"
                        },
                        new
                        {
                            BreedID = 117,
                            BreedName = "Portuguese Water Dog"
                        },
                        new
                        {
                            BreedID = 118,
                            BreedName = "Pug"
                        },
                        new
                        {
                            BreedID = 119,
                            BreedName = "Puli"
                        },
                        new
                        {
                            BreedID = 120,
                            BreedName = "Pumi"
                        },
                        new
                        {
                            BreedID = 121,
                            BreedName = "Rat Terrier"
                        },
                        new
                        {
                            BreedID = 122,
                            BreedName = "Redbone Coonhound"
                        },
                        new
                        {
                            BreedID = 123,
                            BreedName = "Rhodesian Ridgeback"
                        },
                        new
                        {
                            BreedID = 124,
                            BreedName = "Rottweiler"
                        },
                        new
                        {
                            BreedID = 125,
                            BreedName = "Saint Bernard"
                        },
                        new
                        {
                            BreedID = 126,
                            BreedName = "Saluki"
                        },
                        new
                        {
                            BreedID = 127,
                            BreedName = "Samoyed"
                        },
                        new
                        {
                            BreedID = 128,
                            BreedName = "Schipperke"
                        },
                        new
                        {
                            BreedID = 129,
                            BreedName = "Shetland Sheepdog"
                        },
                        new
                        {
                            BreedID = 130,
                            BreedName = "Shiba Inu"
                        },
                        new
                        {
                            BreedID = 131,
                            BreedName = "Shih Tzu"
                        },
                        new
                        {
                            BreedID = 132,
                            BreedName = "Siberian Husky"
                        },
                        new
                        {
                            BreedID = 133,
                            BreedName = "Silky Terrier"
                        },
                        new
                        {
                            BreedID = 134,
                            BreedName = "Smooth Fox Terrier"
                        },
                        new
                        {
                            BreedID = 135,
                            BreedName = "Spanish Water Dog"
                        },
                        new
                        {
                            BreedID = 136,
                            BreedName = "Staffordshire Bull Terrier"
                        },
                        new
                        {
                            BreedID = 137,
                            BreedName = "Standard Schnauzer"
                        },
                        new
                        {
                            BreedID = 138,
                            BreedName = "Swedish Vallhund"
                        },
                        new
                        {
                            BreedID = 139,
                            BreedName = "Tibetan Mastiff"
                        },
                        new
                        {
                            BreedID = 140,
                            BreedName = "Tibetan Spaniel"
                        },
                        new
                        {
                            BreedID = 141,
                            BreedName = "Tibetan Terrier"
                        },
                        new
                        {
                            BreedID = 142,
                            BreedName = "Vizsla"
                        },
                        new
                        {
                            BreedID = 143,
                            BreedName = "Weimaraner"
                        },
                        new
                        {
                            BreedID = 144,
                            BreedName = "Welsh Springer Spaniel"
                        },
                        new
                        {
                            BreedID = 145,
                            BreedName = "Welsh Terrier"
                        },
                        new
                        {
                            BreedID = 146,
                            BreedName = "West Highland White Terrier"
                        },
                        new
                        {
                            BreedID = 147,
                            BreedName = "Whippet"
                        },
                        new
                        {
                            BreedID = 148,
                            BreedName = "Xoloitzcuintli"
                        },
                        new
                        {
                            BreedID = 149,
                            BreedName = "Yorkshire Terrier"
                        },
                        new
                        {
                            BreedID = 150,
                            BreedName = "Australian Terrier"
                        },
                        new
                        {
                            BreedID = 151,
                            BreedName = "Black Russian Terrier"
                        },
                        new
                        {
                            BreedID = 152,
                            BreedName = "Brittany Spaniel"
                        },
                        new
                        {
                            BreedID = 153,
                            BreedName = "Catahoula Leopard Dog"
                        },
                        new
                        {
                            BreedID = 154,
                            BreedName = "Cavalier Spaniel"
                        },
                        new
                        {
                            BreedID = 155,
                            BreedName = "Curly-Coated Retriever"
                        },
                        new
                        {
                            BreedID = 156,
                            BreedName = "English Bulldog"
                        },
                        new
                        {
                            BreedID = 157,
                            BreedName = "English Foxhound"
                        },
                        new
                        {
                            BreedID = 158,
                            BreedName = "Finnish Spitz"
                        },
                        new
                        {
                            BreedID = 159,
                            BreedName = "Glen of Imaal Terrier"
                        },
                        new
                        {
                            BreedID = 160,
                            BreedName = "Great Pyrenean"
                        },
                        new
                        {
                            BreedID = 161,
                            BreedName = "Irish Red and White Setter"
                        },
                        new
                        {
                            BreedID = 162,
                            BreedName = "Lakeland Terrier"
                        },
                        new
                        {
                            BreedID = 163,
                            BreedName = "Lowchen"
                        },
                        new
                        {
                            BreedID = 164,
                            BreedName = "Mexican Hairless Dog"
                        },
                        new
                        {
                            BreedID = 165,
                            BreedName = "Norwegian Buhund"
                        },
                        new
                        {
                            BreedID = 166,
                            BreedName = "Norwegian Lundehund"
                        },
                        new
                        {
                            BreedID = 167,
                            BreedName = "Otterhound"
                        },
                        new
                        {
                            BreedID = 168,
                            BreedName = "Petit Basset Griffon Vendeen"
                        },
                        new
                        {
                            BreedID = 169,
                            BreedName = "Portuguese Podengo"
                        },
                        new
                        {
                            BreedID = 170,
                            BreedName = "Pudelpointer"
                        },
                        new
                        {
                            BreedID = 171,
                            BreedName = "Shiloh Shepherd"
                        },
                        new
                        {
                            BreedID = 172,
                            BreedName = "Skye Terrier"
                        },
                        new
                        {
                            BreedID = 173,
                            BreedName = "Soft-Coated Wheaten Terrier"
                        },
                        new
                        {
                            BreedID = 174,
                            BreedName = "Stabyhoun"
                        },
                        new
                        {
                            BreedID = 175,
                            BreedName = "Sussex Spaniel"
                        },
                        new
                        {
                            BreedID = 176,
                            BreedName = "Swedish Lapphund"
                        },
                        new
                        {
                            BreedID = 177,
                            BreedName = "Taiwan Dog"
                        },
                        new
                        {
                            BreedID = 178,
                            BreedName = "Thai Ridgeback"
                        },
                        new
                        {
                            BreedID = 179,
                            BreedName = "Tosa"
                        },
                        new
                        {
                            BreedID = 180,
                            BreedName = "Treeing Walker Coonhound"
                        },
                        new
                        {
                            BreedID = 181,
                            BreedName = "Volpino Italiano"
                        },
                        new
                        {
                            BreedID = 182,
                            BreedName = "Wirehaired Vizsla"
                        },
                        new
                        {
                            BreedID = 183,
                            BreedName = "Wetterhoun"
                        },
                        new
                        {
                            BreedID = 184,
                            BreedName = "Alano Español"
                        },
                        new
                        {
                            BreedID = 185,
                            BreedName = "Central Asian Shepherd"
                        },
                        new
                        {
                            BreedID = 186,
                            BreedName = "Kangal"
                        },
                        new
                        {
                            BreedID = 187,
                            BreedName = "Estrela Mountain Dog"
                        },
                        new
                        {
                            BreedID = 188,
                            BreedName = "Chinook"
                        },
                        new
                        {
                            BreedID = 189,
                            BreedName = "Bohemian Shepherd"
                        },
                        new
                        {
                            BreedID = 190,
                            BreedName = "Blue Lacy"
                        },
                        new
                        {
                            BreedID = 191,
                            BreedName = "Danish-Swedish Farmdog"
                        },
                        new
                        {
                            BreedID = 192,
                            BreedName = "Dutch Smoushond"
                        },
                        new
                        {
                            BreedID = 193,
                            BreedName = "Old Danish Pointer"
                        },
                        new
                        {
                            BreedID = 194,
                            BreedName = "Romanian Raven Shepherd Dog"
                        },
                        new
                        {
                            BreedID = 195,
                            BreedName = "Shikoku"
                        },
                        new
                        {
                            BreedID = 196,
                            BreedName = "Telomian"
                        },
                        new
                        {
                            BreedID = 197,
                            BreedName = "Transylvanian Hound"
                        },
                        new
                        {
                            BreedID = 198,
                            BreedName = "Tibetan Kyi Apso"
                        },
                        new
                        {
                            BreedID = 199,
                            BreedName = "Yakutian Laika"
                        },
                        new
                        {
                            BreedID = 200,
                            BreedName = "Yorkshire Terrier"
                        });
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusID")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("QRCodeID")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("OrderStatusID");

                    b.HasIndex("QRCodeID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Backend.Models.PetCard", b =>
                {
                    b.Property<int>("PetCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetCardID"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportantInformation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MobilePhone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PetCardID");

                    b.HasIndex("PetID");

                    b.HasIndex("UserID");

                    b.ToTable("PetCards");
                });

            modelBuilder.Entity("Backend.Models.PetProfile", b =>
                {
                    b.Property<int>("PetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetID"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BreedID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHavingCard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTransferred")
                        .HasColumnType("bit");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("QRCodeID")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpecialNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PetID");

                    b.HasIndex("BreedID");

                    b.HasIndex("QRCodeID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("PetProfiles");
                });

            modelBuilder.Entity("Backend.Models.QRCode", b =>
                {
                    b.Property<int>("QRCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QRCodeID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateGenerated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsScannedForFirstTime")
                        .HasColumnType("bit");

                    b.Property<int?>("PetProfileID")
                        .HasColumnType("int");

                    b.Property<string>("QRCodeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCodeImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QRCodeID");

                    b.ToTable("QRCodes");
                });

            modelBuilder.Entity("Backend.Models.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            StatusName = "Pending",
                            Type = "Order"
                        },
                        new
                        {
                            StatusID = 2,
                            StatusName = "Completed",
                            Type = "Order"
                        },
                        new
                        {
                            StatusID = 3,
                            StatusName = "Canceled",
                            Type = "Order"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAccountTransferRequested")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.HasOne("Backend.Models.Status", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend.Models.QRCode", "QRCode")
                        .WithMany()
                        .HasForeignKey("QRCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("QRCode");
                });

            modelBuilder.Entity("Backend.Models.PetCard", b =>
                {
                    b.HasOne("Backend.Models.PetProfile", "PetProfile")
                        .WithMany()
                        .HasForeignKey("PetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.PetProfile", b =>
                {
                    b.HasOne("Backend.Models.DogBreed", "DogBreed")
                        .WithMany()
                        .HasForeignKey("BreedID");

                    b.HasOne("Backend.Models.QRCode", "QRCode")
                        .WithOne("PetProfile")
                        .HasForeignKey("Backend.Models.PetProfile", "QRCodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DogBreed");

                    b.Navigation("QRCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.QRCode", b =>
                {
                    b.Navigation("PetProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
