version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "ScanMyPaws2806"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: ./Backend/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    environment:
      server: "sqlserver"
      port: "1433"
      database: "ScanMyPaws"
      dbuser: "sa"
      password: "ScanMyPaws2806"
    restart: always

  scanmypaws:
    build:
      context: ./WebApplication/scanmypaws
    container_name: scanmypaws
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    environment:
      - VITE_APP_API_BASE_URL=http://backend:5000

  eshop:
    build:
      context: ./Eshop/eshop
    container_name: eshop
    ports:
      - "4000:80"
    depends_on:
      - backend
    restart: always

volumes:
  sqlserver_data:
